services:
  pg:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: user
    ports:
      - 5432:5432
    expose:
      - 5432
  migrate:
    build: .
    depends_on:
      - "pg"
    command: sh -c "sleep 10; npm run migrate"
  seed:
    build: .
    depends_on:
      - "migrate"
    command: sh -c "sleep 15; npm run seed"
  app:
    build: .
    depends_on:
      - "seed"
    ports:
      - 8080:8080
    expose:
      - 8080
    command: sh -c "sleep 20; npm start"
